### ISSUE TITLE
Remove g2p?

### ISSUE THREAD

**Issue by roedoejet** [MotherTongues/mothertongues#6]
Since we have moved to a weighted edit distance, we don't need compare forms anymore and so we can remove g2p as a dependency.

**Comment by roedoejet** [comment]
The only reason not to remove g2p would be if we wanted to also keep support for the compare-form based unweighted search. I'm not yet sure if we want to do that.

**Comment by pandersity** [comment]
just adding more info to this thread. As it stands, g2p needs to be installed in order to run unit tests locally (I had to manually pip install it into my poetry env).

**Comment by dhdaines** [comment]
Yes in fact it seems that it is necessary just to run the CLI, e.g.:
```
$ poetry run mothertongues
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dhd/work/p2wilrc/mothertongues-mothertongues/mothertongues/cli.py", line 14, in <module>
    from mothertongues.config import SchemaTypes, get_schemas
  File "/home/dhd/work/p2wilrc/mothertongues-mothertongues/mothertongues/config/__init__.py", line 3, in <module>
    from mothertongues.config.models import (
  File "/home/dhd/work/p2wilrc/mothertongues-mothertongues/mothertongues/config/models.py", line 26, in <module>
    from mothertongues.utils import string_to_callable
  File "/home/dhd/work/p2wilrc/mothertongues-mothertongues/mothertongues/utils.py", line 9, in <module>
    from g2p import Mapping, Transducer
ModuleNotFoundError: No module named 'g2p'
```
As a side note, I tried adding it to my environment with `poetry add g2p` (is this the right command??) and this took a surprisingly long time.  Really, I do not like `poetry` at all.

**Comment by pandersity** [comment]
I used a regular pip install in my poetry env

`poetry run pip install g2p`

hth!
